# cfgs/clipcurl_config.yaml
defaults:
  - _self_
  - task@_global_: walker_walk

# task
env: dmc
task_name: walker_walk
frame_stack: 3
action_repeat: 2
discount: 0.99

# train
num_seed_frames: 4000

# eval
eval_every_frames: 10000
num_eval_episodes: 10

# snapshot
save_snapshot: true
save_snapshot_every: 50000

# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256

# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: true

# wandb
use_wandb: false
wandb_proj_name: 'clipcurl'

# experiment
experiment: exp
lr: 1e-3
feature_dim: 50
name: clipcurl

# agent
agent:
  _target_: algos.clipcurl.CLIPCURLAgent
  obs_shape: ??? 
  action_shape: ??? 
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  
  # 新增父类必需的参数
  stddev_schedule: 'linear(1.0, 0.1, 1000000)'  # 
  stddev_clip: 0.3  
  
  # CLIPCURL
  clip_model_name: 'ViT-B/32'
  clip_reward_scale: 0.1
  curl_weight: 1.0
  clip_weight: 0.1

# hydra
hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${name}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${name}/${now:%H%M}_${experiment}
    subdir: ${hydra.job.num}